netty:
  port: 8888 # Netty Server port
mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.springboot.springbootmybatisxml.model
spring:
  datasource:
    name: cs552
    url: jdbc:mysql://127.0.0.1:3306/cs552
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver


